### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by Smoodys** [bash163/openload-link#1]
Don't know how to use it, anyone can help? full steps pls

**Comment by bash163** [comment]
It uses JavaScript promises. You can either use await/async or a .then()

**Comment by Smoodys** [comment]
Still dont know how to use it :(, can u provide a full project with this code?

**Comment by bash163** [comment]
```
openload('https://openload.co/embed/hdjdkdjdn').then(link => console.log(link))
```
